name: Schematron test

on:
  workflow_dispatch: # trigger manually

env:
  SCHEMATRON_FILES: utils/schematron
  DRIVER_FILE: source/mei-source.xml
  RNG_FILE: https://raw.githubusercontent.com/music-encoding/schema/master/dev/mei-all.rng
  
  SCHEMATRON_EXTRACT: utils/schematron/ExtractSchFromRNG-2.xsl
  SCHEMATRON_PREPROCESS: utils/schematron/iso_dsdl_include.xsl
  SCHEMATRON_EXPAND: utils/schematron/iso_abstract_expand.xsl
  SCHEMATRON_COMPILE: utils/schematron/iso_svrl_for_xslt2.xsl
  SCHEMATRON_LOCATION: schematron
  
  PATH_TO_SAXON_JAR: lib/saxon/saxon9he.jar
  
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  PURPLE: '\033[0;35m'
  NORM: '\033[0m'  # No Color

jobs:
  build_schematron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Setup SaxonHE
        run: ant -noinput -buildfile build.xml init
      
      - name: Create directory if needed
        run: | 
          if [ ! -d $SCHEMATRON_LOCATION ]; then
            echo -e "${PURPLE}Creating schematron directory${NORM}"
            mkdir -p $SCHEMATRON_LOCATION
          fi
      
      - name: Create outputfile
        run: echo schematron_rules=$(basename ${RNG_FILE%%.*}).xsl >> $GITHUB_ENV
      
      - name: Make tempdir
        run: echo tempdir=$(mktemp -d) >> $GITHUB_ENV
      
      - name: Extract rules from the RNG schema
        # TODO: $rngfile; 
        run: java -jar $PATH_TO_SAXON_JAR -versionmsg:off -s:$RNG_FILE -xsl:$SCHEMATRON_EXTRACT -o:${tempdir}/schematron-rules.sch

      - name: Preprocess
        run: java -jar $PATH_TO_SAXON_JAR -versionmsg:off -s:${tempdir}/schematron-rules.sch -xsl:$SCHEMATRON_PREPROCESS -o:${tempdir}/schematron-preprocess.sch
      
      - name: Expand
        run: java -jar $PATH_TO_SAXON_JAR -versionmsg:off -s:${tempdir}/schematron-preprocess.sch -xsl:$SCHEMATRON_EXPAND -o:${tempdir}/schematron-expand.sch
        
      - name: Compile
        run: java -jar $PATH_TO_SAXON_JAR -versionmsg:off -s:${tempdir}/schematron-expand.sch -xsl:$SCHEMATRON_COMPILE -o:${SCHEMATRON_LOCATION}/${schematron_rules}

      - name:  Remove tempdir
        run: rm -r $tempdir

      - name: Hooray
        run: echo -e "${GREEN} Finished generating Schematron for ${rngfile}${NORM}"

      - name: Validate
        run: ls -R

