name: Schematron test

on:
  workflow_dispatch: # trigger manually

env:
  SCHEMATRON_FILES: utils/schematron
  DRIVER_FILE: source/mei-source.xml
  
  SCHEMATRON_EXTRACT: utils/schematron/ExtractSchFromRNG-2.xsl
  SCHEMATRON_PREPROCESS: utils/schematron//iso_dsdl_include.xsl
  SCHEMATRON_EXPAND: utils/schematron/iso_abstract_expand.xsl"
  SCHEMATRON_COMPILE: utils/schematron/iso_svrl_for_xslt2.xsl"
  SCHEMATRON_LOCATION: schematron
  
  PATH_TO_SAXON_JAR: lib/saxon/saxon9he.jar

  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  PURPLE: '\033[0;35m'
  NORM: '\033[0m'  # No Color

jobs:
  build_schematron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install SaxonHE
        run: | 
          sudo apt-get update -y
          sudo apt-get install -y libsaxon-java
      
      - name: Validate
        run: | 
          dpkg -L libsaxon-java
      
      - name: Create directory if needed
        run: | 
          if [ ! -d $SCHEMATRON_LOCATION ]; then
            echo -e "Creating schematron directory"
            mkdir -p $SCHEMATRON_LOCATION
          fi
      
      - name: Make tempdir
        run: echo tempdir=$(mktemp -d) >> $GITHUB_ENV
      
      - name: Extract rules from the RNG schema
        # TODO: $rngfile; 
        run: java -jar $PATH_TO_SAXON_JAR -versionmsg:off -s:$rngfile -xsl:$SCHEMATRON_EXTRACT -o:${tempdir}/schematron-rules.sch

      - name: Preprocess
        run: java -jar $PATH_TO_SAXON_JAR -versionmsg:off -s:${tempdir}/schematron-rules.sch -xsl:$SCHEMATRON_PREPROCESS -o:${tempdir}/schematron-preprocess.sch
      
      - name: Expand
        run: java -jar $PATH_TO_SAXON_JAR -versionmsg:off -s:${tempdir}/schematron-preprocess.sch -xsl:$SCHEMATRON_EXPAND -o:${tempdir}/schematron-expand.sch
        
      - name: Compile
        run: java -jar $PATH_TO_SAXON_JAR -versionmsg:off -s:${tempdir}/schematron-expand.sch -xsl:$SCHEMATRON_COMPILE -o:${SCHEMATRON_LOCATION}/${schematron_rules}

      - name:  Remove tempdir
        run: rm -r $tempdir

      - name: Hooray
        run: echo -e "${GREEN} Finished generating Schematron for ${rngfile}${NORM}"


